# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

# Trigger pipeline on push to main or tag creation
trigger:
  branches:
    include:
    - main
    - refs/tags/*

# Trigger pipeline on pull request, but only for testing (no release)
pr:
  branches:
    include:
    - main

variables:
  CIBW_SKIP: 'cp27-* cp35-*'

jobs:
- job: Testing
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - script: |
      python -m pip install --upgrade pip
      pip install .
    displayName: 'Install Dependencies'

  - script: |
      pip install pytest tensorboard pytest-azurepipelines yapf
      pytest -v
    displayName: 'Run Pytests'

# Build and Release job
- job: BuildAndRelease
  pool:
    vmImage: 'ubuntu-latest'

  # Condition to trigger only on successful builds from tags or 'main'
  condition: |
    and(succeeded(),
        or(startsWith(variables['Build.SourceBranch'], 'refs/tags/'),
           eq(variables['Build.SourceBranch'], 'refs/heads/main')))

  steps:
  - bash: |
      python3 setup.py sdist bdist_wheel
    displayName: 'Build source and wheel distribution'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'dist'
      artifactName: 'python-package'
    displayName: 'Publish Build Artifacts'

  # Publish to PyPI only if this is a tagged release (no pre-release tags)
  - script: |
      python -m pip install --upgrade twine
      twine upload --non-interactive dist/* --skip-existing

    displayName: 'Publish to PyPI'
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')